### ISSUE TITLE
Add Access-Control-Allow-Origin to respnse header for cross domain requests

### ISSUE THREAD

**Issue by SimonMonecke** [flosell/lambdacd#1]
To test our build monitor I need to run it on my develop machine located in another domain. Because of this the monitor doesn't have the permission to request the cctray of the pipeline.
Please add
```
"Access-Control-Allow-Origin" "*" 
```
to the response header to enable cross domain monitoring. Because of security risks I would suggest a fourth optional parameter for the function *cctray-handler-for*. You can just make a simple signature switch to have a default value ("*") and let people restrict requests to their domain if they want it.

Regards,
  Simon

**Comment by flosell** [comment]
see flosell/lambdacd-cctray#1
