### ISSUE TITLE
Git clone using params

### ISSUE THREAD

**Issue by rodrigomaia17** [flosell/lambdacd#107]
I am using lambdaCD in a huge repository, and I don't need to clone the entire repository history to run my tests. This is taking a long time now and I would like to clone it using some params like `--depth 1`. 

Is there a way to do this now?

**Comment by flosell** [comment]
LambdaCDs git support doesn't support something like this out of the box right now (neither does the rebuilt, JGit based lambdacd-git library at this point: flosell/lambdacd-git#11). 

At the moment, your best option would probably be to hand-roll the clone step by combining [`with-workspace`](https://github.com/flosell/lambdacd/wiki/Control-Flow#with-workspace) and `bash`: 

```clojure
(defn clone-repo [args ctx]
  (shell/bash ctx (:cwd args) "git clone <somerepo> --depth 1"))

(def pipeline-structure
  `(; ...
    (with-workspace
      clone
      do-something)))

```

**Comment by rodrigomaia17** [comment]
Thank you @flosell 

Congratulations for this awesome project! (:

**Comment by flosell** [comment]
Glad you like it! 

Closing this issue for now, feel free to reopen or create a new one if you run into issues or have other questions.
