### ISSUE TITLE
cancel waiting steps

### ISSUE THREAD

**Issue by fhopeman** [flosell/lambdacd#114]
Hey,

My scenario:
```
(alias "container-step" (either
         (run
           (do-something-1)
           (do-something-2))
         wait-for-manual-trigger))
```

I've two different ways to pass the container-step:

1. `do-something-1` and `do-something-2` are passed successfully
2. `wait-for-manual-trigger` is clicked

If do-something-1 or do-something-2 are failing, I've the possibility to pass the `container-step` by clicking wait-for-manual-trigger. But in some cases I want to cancel the whole step and want the whole `container-step` to be red.

Is there a way to do that?

**Comment by flosell** [comment]
Hi, 

I'm not sure if I got what you were trying to do, so I'll try to rephrase: 
The snippet you describe works like you intended, the only thing missing is a way to cancel the wait-for-manual-trigger and turn everything red. The scenario being something like: 
* do-something-1 and do-something-2 are some checks, the pipeline should continue when they are green
* triggering wait-for-manual-trigger indicates an override, "I want to keep going even though the checks are red"
* (missing): I want to make it explicit that I looked at the failing check and I wanted to stop the pipeline, turning it red. 

Three things come to mind: 

* re-mapping the `:killed` status returned from wait-for-manual-trigger: 

  ```clojure
  (defn wait-or-die [args ctx]
    (let [wait-result (wait-for-manual-trigger args ctx)]
      (if (= :killed (:status wait-result))
        (assoc wait-result :status :failure)
        wait-result)))
  ```
  This would make the `wait-or-die` step wait and return failure if the kill-button is clicked. `either` would then fail if the `do-something` steps also failed. 
* composing some logic out of `in-parallel` and `either`: `in-parallel` kind of works like AND, `either` kind of like OR. Might make your pipeline less readable if used too much. 
* implement a custom control-flow step: this might sound trickier than it actually is. `either`, `in-parallel` and so on are nothing special, they are normal steps that can execute other steps and you can implement your own variation to control when the child-steps are executed and how their results are interpreted. Maybe look at [`junction`](https://github.com/flosell/lambdacd/blob/master/src/clj/lambdacd/steps/control_flow.clj#L105) as an example

**Comment by fhopeman** [comment]
I think the point 

> I want to make it explicit that I looked at the failing check and I wanted to stop the pipeline, turning it red.

is the most important one. The only thing which is missing is a kill button for waiting steps.

Is that in the roadmap?

**Comment by flosell** [comment]
Ah, right, I totally missed this part! It's on the roadmap now, #115. As far as I can see right now, this should be straightforward to change. 

It also seems to be purely a UI problem, I'd guess if you sent a POST to `/builds/<buildnumber>/<step-id>/kill` you'd be able to kill the step.

**Comment by fhopeman** [comment]
thank you :)
