### ISSUE TITLE
Printer overwrites output of first part in step with two parts

### ISSUE THREAD

**Issue by BeneStem** [flosell/lambdacd#119]
Moin Flo,

if you have a step with two parts the output of the second part overwrites the output of the first part.
Can you fix that in lambdacd itself or do we need to do sth in a different way in out code?

Small example:

(defn marathon-deploy [^:hide environment]
  (fn [{{version :version} :global cwd :cwd} ctx]
    (let [config (:config ctx)
          vertical (:vertical config)
          app-name (:app-name config)]
      (marathon-deploy/deploy ;first part with printer and output
        ctx
        (marathon-config/with-image
          ((:marathon-config-fn config) environment config)
          (helper/docker-pull-image-name vertical app-name version)))
      (shell/bash ;second part
        ctx cwd
        (str "echo \"OVERWRITES THE FIRST PART\”")))))

If you need more information just name ist

That you for your help!
Greetz
/ben

**Comment by flosell** [comment]
Hi Ben, 

I think your example was cut off right where it would be interesting, i.e. what's inside the `marathon-deploy` step. 
I'm just taking a wild guess and try to give an answer without getting the question :) 

If you want to assemble a build step out of several parts, you might find the `chain-steps` and `chaining` utilities useful: https://github.com/flosell/lambdacd/wiki/Step-Support#chain-steps-args-ctx--steps

As an example: 
```clojure
(defn do-stuff [args ctx]
  (support/chaining args ctx
                    (shell/bash support/injected-ctx "/" "echo one && sleep 10 && echo  two")
                    (shell/bash support/injected-ctx "/" "echo three && sleep 10 && echo four")))
```

It's one of the lesser used features of LambdaCD and therefore doesn't work quite as well as I'd like it to be (e.g. #120 which I just found writing the example) but can be very powerful to write more complex build steps. 

Let me know if I hit your question or you needed something completely different :)

**Comment by BeneStem** [comment]
Christian is going to try this out within the next days.

I am on vacation for two weeks.
If he won’t do it I will do it after my vacation.

Thank you for the quick answer :)

Greetings
/ben

**Comment by flosell** [comment]
Happy to help. I'm closing this issue for now, feel free to re-open or open an new one in case you run into issues or have other questions.
