### ISSUE TITLE
Chaining overwrites existing intermediate output while running

### ISSUE THREAD

**Issue by flosell** [flosell/lambdacd#120]
Chaining is meant to execute several steps within a single step, e.g. 

```clojure
(defn do-stuff [args ctx]
  (support/chaining args ctx
                    (shell/bash support/injected-ctx "/" "echo one && sleep 10 && echo two")
                    (shell/bash support/injected-ctx "/" "echo three && sleep 10 && echo four")))
```

In the end, the output looks like expected: 

```
one 
two 
three
four
```
But while the second chained command is running, you only see its output in the UI: 
```
three
```

I'd expect that the intermediate result shows the complete picture as well, e.g. 

```
one 
two
three
```

**Comment by BeneStem** [comment]
Ok, so the issue we are facing is a bug and we can't do anything about it? :P

**Comment by flosell** [comment]
Likely, yes. I already started working on this issue but it wasn't trivial to solve before being swamped with other duties for the last couple of weeks. The next weeks should be a bit more quiet for me so hopefully I have an update on this soon.

**Comment by BeneStem** [comment]
No problem.
We split the step into two steps ;)
That works as a workaround.

**Comment by flosell** [comment]
Should be fixed, will be in next release.
