### ISSUE TITLE
Question: Is it possible to run lambdacd in none-server mode?

### ISSUE THREAD

**Issue by philwinder** [flosell/lambdacd#127]
I'd like a built tool that is not running as a server, so that I can integrate it with other tools. 

Is it possible to take the "pipeline" part of the codebase and run that on its own, like a cli app?

**Comment by flosell** [comment]
LambdaCD is a library, you pull in the parts you need. So what you are suggesting is not the default use-case but should be possible without jumping through too many hoops: 

You'll need a way to run your pipeline-code. In server-mode, [runners](https://github.com/flosell/lambdacd/blob/master/src/clj/lambdacd/runners.clj) are resposible to run it in a loop. You probably just need the `lambdacd.internal.execution/run` function. 

Then you'll probably want some way to get information out of the pipeline run. The [event-bus](https://github.com/flosell/lambdacd/wiki/Event-Bus) should give you updates on what's happening while the pipeline is running. This is the raw information flow LambdaCD uses internally. If you are looking for more aggregated information you could also look at what the [Web-UI](https://github.com/flosell/lambdacd/blob/master/src/clj/lambdacd/ui/api.clj) does. 

Here's an example of how this could look like: A CLI application that just runs your pipeline once and logs the internal step updates to stdout: https://gist.github.com/flosell/ed829b8b554c3f7af897de918e3d4e44

**Comment by flosell** [comment]
Do you need more assistance with this? If not, I'll close this issue

**Comment by philwinder** [comment]
That's great, thanks.
