### ISSUE TITLE
Export pipeline state in prometheus format

### ISSUE THREAD

**Issue by f0** [flosell/lambdacd#142]
it would be nice to have the pipeline state exported in the https://prometheus.io/ format (https://prometheus.io/docs/instrumenting/exposition_formats/). (to monitor build failures)

i think the following should exposed for each pipeline (and / or step?)

duration
status 
last succesfull status
last build date
...

**Comment by flosell** [comment]
I can see this as an interesting feature. 
However, to keep the core of lambdacd focused, I'd prefer to keep features like this out of the core and in separate libraries that users pull in when needed, along the lines of how cctray support was implemented in [lambdacd-cctray](https://github.com/flosell/lambdacd-cctray). 

I'd imagine prometheus-support could be implemented in a very similar manner. Just keep in mind that some aspects of the state-interface that lambdacd-cctray uses were deprecated in the last lambdacd-release. This should be fixed soon (see flosell/lambdacd-cctray#11 for details)

**Comment by flosell** [comment]
Since I am currently not using prometheus, I'd welcome someone contributing this feature as a separate library.

**Comment by flosell** [comment]
losing for now, feel free to reopen or ping me if you need help building such a feature
