### ISSUE TITLE
Retrigger mechanism is broken

### ISSUE THREAD

**Issue by SimonMonecke** [flosell/lambdacd#146]
Hi Flo,

we just updated our pipelines to version 0.11.0 to test the new version (2.0.0) of lambdacd-mongodb. After this update the retrigger mechanism was broken. You can click on the retrigger button but then you only see a white page with the centered text "loading...":

![lambdacd-retrigger](https://cloud.githubusercontent.com/assets/4587790/21188845/f7ebbfc2-c21c-11e6-9854-ccacd50127ca.png)

In our local mongoDB we can see the new build #3 but it only has a pipeline-state. The structure is missing.
lambdacd-mongodb 2.0.0 uses the new protocols  (lambdacd/src/clj/lambdacd/state/protocols.clj). Maybe you has forgotten a call of _consume-pipeline-structure_ after copying the state. We have the same problem if we deactivate lambdacd-mongo ;)

Regards,
  Simon

**Comment by flosell** [comment]
Hi Simon, 

thanks for reporting this and thanks for keeping lambdacd-mongodb up to date! 

Your guess was almost right: LambdaCD did call `consume-pipeline-structure` when retriggering it just did so for the already existing build, not the new one. 

It should be fixed now and I'll release it soon. 

Cheers, 
Florian

**Comment by flosell** [comment]
Released as [0.12.0](https://github.com/flosell/lambdacd/releases/tag/0.12.0)
