### ISSUE TITLE
bidi routes

### ISSUE THREAD

**Issue by kwladyka** [flosell/lambdacd#149]
As i can see lambdacd works only with compojure. It will be nice to use bidi instead. Just have this possibility in flexible way.

**Comment by flosell** [comment]
Hi, thanks for the suggestion. 
I am a bit hesitant to add bidi as another dependency to the LambdaCD core. 

I'm not super familiar with bidi but aren't compojure routes (like what you get from `ui-for`) also just ring-handlers you could use in bidi routes? Does that make sense for what you are trying to achieve?

**Comment by kwladyka** [comment]
I was trying to use it with bidi. It doesn't work. But maybe is some secret way for that which i don't know. The ring handler will be ok, but what i see lambdacd return the compojure routes.

Adding the bidi as next dependency is probably not the right solution. Probably lambdacd shouldn't have even compojure as dependency. Instead of that should return ring responses.

```clojure
(routes
     (context "/api" [] (api/rest-api pipeline))
     (route/resources "/" {:root "public"})
     (GET "/" [] (ui-page/ui-page pipeline)))
```

As i understand lambdacd returns ring responses for routes. So probably i can create my own routes and add there `(api/rest-api pipeline)` etc. maybe. Not use `ui-for` I didn't try yesterday.

**Comment by flosell** [comment]
If using a compojure route within bidi doesn't work, creating your own routes sounds like a reasonable thing to do. 
Medium-term, I'm planning to split the UI out into a separate project anyway, then I'll probably also rethink what to expose, what dependencies are necessary and how to do routing. 

Just to understand your requirements a bit better: What is it you are trying to achieve where bidi-routes would be beneficial for you?

**Comment by kwladyka** [comment]
I wanted just give a suggestion it could be done as for example http://clojure-liberator.github.io/liberator/ conception which can work with whatever route solution. I just use bidi everywhere and prefer more then compojure. So my first thought was why lambdacd stick to compojure. But for that case of use i am not sure it really matter at that moment. I mean it will be good to remove that dependency as the force one, but probably it is not the highest priority now. Maybe i wrote that issue too fast in the context of priorities. At that moment it is something what it will be like "nice to change".

So answering your question. I wanted use bidi only because i prefer to use it over compojure :) Then my first thought was lambdacd shouldn't done this in that way and i wrote that issue. Sorry if disappointed you :)

**Comment by flosell** [comment]
:) No worries, it's always good to hear feedback, keep it coming! 

And to answer your question, I used compojure because it seemed to be the default choice at the time and I didn't know any better :)

**Comment by flosell** [comment]
@kwladyka: As far as I understand you, there is nothing immediate to be done here so I'll close this for now and keep your suggestions in mind.
