### ISSUE TITLE
:max-builds doesn't work

### ISSUE THREAD

**Issue by kwladyka** [flosell/lambdacd#150]
```clojure
{:home-dir "builds/dev"
 :name "SB dev -> edge"
 :max-builds 3}
```

<img width="236" alt="screen shot 2017-01-10 at 20 35 09" src="https://cloud.githubusercontent.com/assets/3903726/21821571/50f415da-d774-11e6-9e87-ae5a7d653fbb.png">

```
ls example
build-1 build-2 build-3 build-4 build-5
```

It looks like `:max-builds` does nothing.

**Comment by flosell** [comment]
I haven't bumped the version you get from `lein new lambdacd` in a while, are you sure you are using the most recent version of LambdaCD (check `project.clj`)? `max-builds` should work with versions 0.10.0 upwards.

**Comment by kwladyka** [comment]
I have older version in that case. Thx.
