### ISSUE TITLE
Problem running my-first-pipeline

### ISSUE THREAD

**Issue by Z20171Z24Z1** [flosell/lambdacd#173]
Hi,

I ran the commands:

$ lein new lambdacd my-first-pipeline
$ cd my-first-pipeline
$ lein run

but get the message: Tried to use insecure HTTP repository without TLS.

How can this be resolved?

project.clj file is:

(defproject my-first-pipeline "0.1.0-SNAPSHOT"
            :description "FIXME: write description"
            :url "http://example.com/FIXME"
            :dependencies [[lambdacd "0.13.2"]
                           [lambdaui "0.4.0"]
                           [http-kit "2.2.0"]
                           [org.clojure/clojure "1.7.0"]
                           [org.clojure/tools.logging "0.3.1"]
                           [org.slf4j/slf4j-api "1.7.5"]
                           [ch.qos.logback/logback-core "1.0.13"]
                           [ch.qos.logback/logback-classic "1.0.13"]]
            :profiles {:uberjar {:aot :all}}
            :main my-first-pipeline.core)

Any help much appreciated.

**Comment by flosell** [comment]
Thanks for reporting this. This problem was fixed in #171 but the LambdaCD Template (that `lein new` uses) doesn't use the new release yet. I'll fix this in the next days the latest. 

In the meantime, manually changing the LambdaCD version to `0.13.3` or later (`0.13.4` is the latest at the moment) should fix the problem.

**Comment by flosell** [comment]
Updated the Leiningen template. `lein new` should now generate LambdaCD projects with a dependency on lambdacd 0.13.4. 
If you already used the template before you might need to remove old versions from your Maven cache: `rm -rf ~/.m2/repository/lambdacd/lein-template` for Leiningen to pull the latest template

**Comment by Z20171Z24Z1** [comment]
Thanks for the reply.  I did clear the repos but found that the lambdaui-0.4.0.pom file still had a reference to     <dependency>
      <groupId>lambdacd</groupId>
      <artifactId>lambdacd</artifactId>
      <version>0.10.0</version>
    </dependency>

I manually changed this to 0.13.4 and I was able to run cmd: lein run without getting the tls error.

Looking inside the 0.10.0.pom file I think the guilty link was:
http://repository.activeeon.com/content/repositories/releases/

**Comment by flosell** [comment]
Sorry about that, when writing my first reply I didn't start from a clean `.m2`-folder so I didn't see that behaviour. I assumed Leiningen would just ignore the LambdaCD-dependency in Lambda UI when you already declared a newer version but it looks like it still tries to download it first... 

sroidl/lambda-ui#101 updated those dependencies in LambdaUI, I'll ping the maintainer to release a new version. 

In the meantime, explicitly excluding the dependency in your `project.clj` should do the trick: 
```clojure
(defproject foobar "0.1.0-SNAPSHOT"
            :description "FIXME: write description"
            :url "http://example.com/FIXME"
            :dependencies [[lambdacd "0.13.4"]
                           [lambdaui "0.4.0" :exclusions [lambdacd]]
                           [http-kit "2.2.0"]
                           [org.clojure/clojure "1.7.0"]
                           [org.clojure/tools.logging "0.3.1"]
                           [org.slf4j/slf4j-api "1.7.5"]
                           [ch.qos.logback/logback-core "1.0.13"]
                           [ch.qos.logback/logback-classic "1.0.13"]]
            :profiles {:uberjar {:aot :all}}
            :main foobar.core)
```

**Comment by flosell** [comment]
New version of lambda-ui was released that contains updated dependencies. Also updated the lambdacd leiningen template to use it. This should fix the dependency-issues.
