### ISSUE TITLE
Does not work with Clojure 1.9

### ISSUE THREAD

**Issue by magnars** [flosell/lambdacd#178]
Have you considered upgrading? There are a few dependencies that does not work with the stricter macro checks in 1.9, but I think bumping dependencies is all it would take to support it.

In case you're wondering, my use case is speccing up my configuration files.

**Comment by flosell** [comment]
Good point. Just fixed a couple of things in the Clojure code, that seems to work alright. The ClojureScript test setup seems to be a bit more tricky, I don't think I'll solve that tonight.

**Comment by flosell** [comment]
Fixed and released as lambdacd 0.14.0. 

You might also need to bump other dependencies to the most recent versions:
* lambdacd-git 0.4.1
* lambdacd-artifacts 0.2.2
* lambdacd-value-stream 0.2.0

sroidl/lambdaui#105 still needs to be merged so Lambda UI is currently not compatible with this release.
