### ISSUE TITLE
empty parameterized-trigger param

### ISSUE THREAD

**Issue by woosley** [flosell/lambdacd#180]
```
(defn some-step-that-echos-foo [{version :version} ctx]
  (shell/bash ctx "/" (str "echo yeah version is" version)))
(defn some-step-that-echos-bar [args ctx]
  (shell/bash ctx "/" "echo bar"))
(defn some-failing-step [args ctx]
  (shell/bash ctx "/" "echo \"i am going to fail now...\"" "exit 1"))
(defn wait-for-version [args ctx]
  (manualtrigger/parameterized-trigger {:version {:desc "version to deploy"}}, ctx))

```
this is my first try to use lambdaCD, I was trying to use parameterized-trigger and output the version imputed on the web, but  the output log is showing just "yeah version is", version is empty.

Is there anything wrong? 

btw, I am wondering if the input can be a select dropdown so user can choose from the list?

**Comment by flosell** [comment]
My guess is this has something to do with the structure of the pipeline. By default, LambdaCD passes the output of one step into the `args` of the next step. If you want a value to be available to all subsequent steps in a pipeline you'll need to explicitly declare this using the `:global` key, like so: 

```clojure
(defn some-step-that-echos-foo [{{version :version} :global} ctx]
  (shell/bash ctx "/" (str "echo yeah version is" version)))

(defn wait-for-version [args ctx]
  (let [result (manualtrigger/parameterized-trigger {:version {:desc "version to deploy"}}, ctx)]
    (assoc result :global {:version (:version result)})))
```

As to your question, can we use a dropdown to input parameters: I like the idea, but it's not the highest thing on my personal list of priorities. I'd welcome a PR though :) 
If you want to take a stab at this, [this UI code](https://github.com/flosell/lambdacd/blob/master/src/cljs/lambdacd/pipeline.cljs#L80) is probably a good point to start.

**Comment by woosley** [comment]
@flosell yeah, it is not a problem anymore, please close this issue.

**Comment by flosell** [comment]
OK, thanks for the feedback!
