### ISSUE TITLE
Sidebar with pipelines.

### ISSUE THREAD

**Issue by Atsman** [flosell/lambdacd#185]
Hello,

While using this great project I have noticed that it should not be hard to implement UI for all pipelines that user defines in his project. I mean something like a homepage with the list of pipelines. I found that I do the same for each pipeline: create the pipeline, start runner, define a link for it and then create a compojure handler for it. 

I think that it is a good idea to abstract that in a way that you can pass a vector of pipelines with a configuration to some function from lambdacd. 

Example of configuration:

```clojure
[{:name :project-pipeline
  :pipeline project-pipeline ; or even like a keyword :namespace/project-pipeline 
  :url "/project"
  :runner :start-one-run-after-another}]
```

What do you think, does that make sense? 

Aleh

**Comment by flosell** [comment]
Yes, that's absolutely possible. Have a look at this example: https://github.com/flosell/lambdacd-cookie-cutter-pipeline-example

I haven't updated this in a while but the basic concepts should still work. You might also find a few interesting pieces in this wiki page: https://github.com/flosell/lambdacd/wiki/Guide:-Pipeline-Structure-Refactoring

I also know some people who built quite advanced setups similar to what you have in mind, I'll try to find out if any of that can be shared

**Comment by Atsman** [comment]
Clear for now. Will thing about standard API in reference UI for it.
