### ISSUE TITLE
UI request rate

### ISSUE THREAD

**Issue by Atsman** [flosell/lambdacd#187]
Hey, 

Let's not send requests for updates each second, because if the server is stuck during load time, requests queue a lot which generates even more load. I think the correct loop is sent a request, wait for a response and then sent a new one.

Regards

**Comment by Atsman** [comment]
Ok will take a look!

**Comment by flosell** [comment]
Fixed in #188 and released as [`0.14.1`](https://github.com/flosell/lambdacd/releases/tag/0.14.1)
