### ISSUE TITLE
Replace less with garden.

### ISSUE THREAD

**Issue by Atsman** [flosell/lambdacd#189]
Hey, you don't mind if i will replace less with [garden](https://github.com/noprompt/garden)?

**Comment by flosell** [comment]
I don't have strong opinions on Stylesheet-Tooling :) Any particular reasoning why you feel garden would be worth the change? 

I personally probably won't invest a lot of time into such a change but I'm curious about garden so if you want to take it on, go for it! Maybe create a `[WIP]` PR so I can give feedback before you invest too much time in case I feel things go into the wrong direction.

**Comment by flosell** [comment]
Haven't heard back on this in a while, closing for now. We can always reopen this if there's interest.
