### ISSUE TITLE
Is it possible to change the structure of a pipeline once it has started

### ISSUE THREAD

**Issue by accammer** [flosell/lambdacd#195]
I was wondering if it was possible to dynamically change a pipeline after it has started.  

I would like to clone a git repository, and based on the structure of what is there, augment the existing pipeline with some extra steps.

I can make the capacity of a step great based on what is found but I am wondering if I could add some steps in directly.

**Comment by flosell** [comment]
depends a bit what you want to achieve. If you want to execute different steps based on some condition, that's relatively straightforward using the [`junction`](https://www.lambda.cd/api-docs/0.14.3/lambdacd.steps.control-flow.html#var-junction) operator that executes one branch of the pipeline versus the other.

If you need something more advanced, control-flow (like `in-parallel`, `junction`, ...) in LambdaCD is implemented as a normal build step; The only thing that's different is the behaviour: it receives child-steps as input and controls their execution. So in theory, you can build any kind of dynamic control flow (use the [implementation](https://github.com/flosell/lambdacd/blob/master/src/clj/lambdacd/steps/control_flow.clj) of the existing control flow operations as examples).

Only one major limitation: For visualisation of the pipeline, LambdaCD uses the pipeline-structure that's defined in code so depending on your custom control-flow, the visualisation might be off. For example, a while-loop control flow would likely be quite straightforward to build but in the UI it would probably look like the same set of steps repeating over and over again (which might or might not be what you want)

**Comment by accammer** [comment]
Thank you for such a quick reply, what I still am not getting is how I would change a pipeline that was already running?  I.e. start with (wait-for-git, clone, (add steps here based on what you have found in clone))

**Comment by flosell** [comment]
if you are going down the control-flow route: you wouldn't "change" the *structure* of the pipeline, you would "change" the *behaviour* of the pipeline, e.g. with `junction` you define two alternative steps (or sets of steps using the [`run`](https://www.lambda.cd/api-docs/0.14.3/lambdacd.steps.control-flow.html#var-run) operator) to be executed depending if a condition is true or false. Example use cases for that would be to add manual approval if another steps output indicates a production deployment is risky or to run certain steps if you are building master but not if you are building a pull-request branch. 

The concept behind this is: you define a set of build steps (clojure functions) that you *might* want to execute. You define a control-flow step (a clojure function that receives child steps as arguments and returns a new build step). The responsibility of this control-flow step is to decide how to execute the childs it receives. 

Does that make more sense? If not, maybe you can describe in a bit more detail (or pseudo-code) what it is you are trying to achieve.

**Comment by accammer** [comment]
Thank you again.  I understand your explanation.
