### ISSUE TITLE
build dependency javasysmon 0.3.6 gone?

### ISSUE THREAD

**Issue by hennr** [flosell/lambdacd#203]
lambdacd includes this repo to resolve "com.jezhumble/javasysmon:0.3.6":
https://dl.bintray.com/gocd-maven-repo/generic/gocd

This repo is not accessbile anymore, I get a "forbidden".

As version 0.3.6 of this dependency is not at maven central I am not able to build lambdaCD any more.
0.3.6 seems to be a somewhat unofficial version so is there anyone having a valid copy of it?
:/

**Comment by floriansellmayr-tw** [comment]
Hi @hennr - thanks for raising this. I guess this dependency got dropped with Bintray sunsetting... 
I also couldn't find any other repository that has it either so I guess the sane thing to do would be to replace this dependency with a different implementation. 
Thankfully, it's only used in a [single place](https://github.com/flosell/lambdacd/blob/e9ba3cebb2d5f0070a2e0e1e08fc85fc99ee7135/src/clj/lambdacd/steps/shell.clj#L24) to kill the whole process tree spawned from a build - In recent JVM versions, this should natively be supported through the [ProcessHandle](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ProcessHandle.html) API so hopefully that's not too complex of a change.

I don't have a lot of capacity to work on LambdaCD right now so a PR would be highly appreciated to fix this!

**Comment by flosell** [comment]
Hi @hennr - thanks for raising this. I guess this dependency got dropped with Bintray sunsetting...
I also couldn't find any other repository that has it either so I guess the sane thing to do would be to replace this dependency with a different implementation.

Thankfully, it's only used in a [single place](https://github.com/flosell/lambdacd/blob/e9ba3cebb2d5f0070a2e0e1e08fc85fc99ee7135/src/clj/lambdacd/steps/shell.clj#L24) to kill the whole process tree spawned from a build - In recent JVM versions, this should natively be supported through the [ProcessHandle](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ProcessHandle.html) API so hopefully that's not too complex of a change.

I don't have a lot of capacity to work on LambdaCD right now so a PR would be highly appreciated to fix this!

**Comment by flosell** [comment]
Thanks @hennr for providing a fix! It's released as [0.14.6](https://github.com/flosell/lambdacd/releases/tag/0.14.6). 
I noticed that there was an issue with LambdaUI having its own dependency to an older version of LambdaCD so in case you are using it, quickest fix is to just exclude this dependency as it would be ignored by the build anyway: 
```clojure
:dependencies [[lambdacd "0.14.6"]
               [lambdaui "1.1.0" :exclusions [lambdacd]]
               ; ...
               [org.clojure/clojure "1.9.0"]]
```

**Comment by hennr** [comment]
You're welcome and thanks for the hint @flosell!
I had to exclude the lambdacd dependency in some more dependencies like lambdacd-git etc. as well, but now we are back on track.

**Comment by tommy-mor** [comment]
I had this problem and fixed it with exclusions for lambdaui and lambdacd-git. thanks for the help
