### ISSUE TITLE
Retriggering container step leaves next step undefined

### ISSUE THREAD

**Issue by redvox** [flosell/lambdacd#26]
It seems that, when you retrigger a step and a new pipeline run is created, the steps that have not run yet are copied as well. Leave their state undefined.
Can you please have a look into that?

**Comment by flosell** [comment]
I wasn't quite able to reproduce this yet but I have a good guess where the problem might be. 

Could you provide the structure of your pipeline (feel free to use different step-names if you don't want details of your infrastructure in the open) and point out the step you were trying to retrigger when this happens?

**Comment by redvox** [comment]
It was a nested step, like
(with-repo (package deploy test))

I triggerd 'deploy' again, which leaves 'test' after finishing deployment undefinded.

**Comment by flosell** [comment]
Fixed and thanks for the example, the bug was easy to reproduce after that!
