### ISSUE TITLE
Insert somekind of checkpoints which stops the pipeline if a criteria is met 

### ISSUE THREAD

**Issue by redvox** [flosell/lambdacd#28]
I have a pipeline with serveral modes and don't want to have serveral pipelines with mustly dulicated steps.
It would be nice to have some kind of checkpoints, where the pipeline is able to stop normally.

Example:
Pipeline: Step1, Step2, Step3, Step4,
Mode 1: Step1-4
Mode 2: Step1-2

Step1, Step2, Checkpoint, Step3, Step4,

Checkpoint (if Mode == 2) exit with success

Thanks!

**Comment by flosell** [comment]
Sounds to me like some kind of an if-then-else container step: 

```clojure
( step1
  step2
  (if-else
    is-mode2
   (run) ;; don't do anything
   (run step3 step4))) ;; else, run rest of the pipeline
```
If you want, you could then wrap this generic function with additional syntactic sugar that matches your precise use case: 

```clojure
(step1
 step2
 (if-not-mode2
   (run step3 step4))) ;; run rest of the pipeline
```

Does this make sense to you?

**Comment by flosell** [comment]
By the way, this should be more or less straightforward to implement, I'd welcome pull requests for this. 
Check out the [implementation of `run`](../blob/master/src/clj/lambdacd/steps/control_flow.clj#L54) for inspiration

**Comment by redvox** [comment]
I will do that, thanks
