### ISSUE TITLE
REST-API: 404 instead of a resource with empty fields

### ISSUE THREAD

**Issue by SimonMonecke** [flosell/lambdacd#42]
Let's assume you start a new LambdaCD instance, which therefore has only one waiting build. Now when you use the REST-API to get information about a particular build and you enter a build number that does not exist, so LambdaCD responds with a resource that has a lot of empty fields:

/pipeline/api/builds/2/
```javascript
[  
   {  
      "children":[  

      ],
      "result":{  

      },
      "name":"wait-for-manual-trigger",
      "type":"step",
      "step-id":[  
         1
      ]
   },
   {  
      "children":[  

      ],
      "result":{  

      },
      "name":"some-step-that-does-nothing",
      "type":"step",
      "step-id":[  
         2
      ]
   },...
```

I suggest to return a 404 status code with an appropriate error message.

**Comment by flosell** [comment]
fixed.
good find, thanks!
