### ISSUE TITLE
LambdaCD Logo?

### ISSUE THREAD

**Issue by alphaone** [flosell/lambdacd#50]
Hi Florian,

are you interested in a Logo for LambdaCD? Every cool project needs a logo, right?

That would be my first try ... What do you think?
![lambda-cd](https://cloud.githubusercontent.com/assets/40830/9877327/6c37b66a-5bbc-11e5-9bdb-7feb413c18e2.png)

Cheers, Torsten

**Comment by fhopeman** [comment]
I like it ;)

**Comment by flosell** [comment]
I like it too! Especially how the colors resemble the clojure colors. Even though I'd need to change the randomly chosen color scheme of the new website :) 

I'd welcome pull requests on this, maybe starting with the readme and the UIs favicon.

**Comment by alphaone** [comment]
Good :)

I will work on that ...
