### ISSUE TITLE
Add a util that rebinds stdout to simplify step output

### ISSUE THREAD

**Issue by flosell** [flosell/lambdacd#60]
Currently, writing output into a step-result either means dealing with `new-printer`, `print-to-output`, `printed-output`. 
(see https://github.com/flosell/lambdacd/blob/master/doc/howto.md#how-do-i-write-to-the-output-so-i-can-see-in-the-ui-what-my-build-step-is-doing)

This is a bit bothersome and, when working with code that's not LambdaCD aware, makes it quite messy. [otto-de/machroput](https://github.com/otto-de/machroput) adds a `print-fn` to the interface just to make it work. 

Maybe we can add a macro that rebinds `stdout` and `stderr` with something that writes to the `result-channel`, accumulates the output and at the end `assoc`s the whole output to the steps result, maybe something like this: 

```clojure
(defn- do-something-that-writes-to-stdout []
  (println "hello")
  (println "world")
  {:status :success})

(defn some-step [arg ctx]
  (with-output
    (do-something-that-writes-to-stdout)))
```

**Comment by alphaone** [comment]
:+1:

**Comment by flosell** [comment]
Basic implementation done: 

```clojure
(defn some-step [args ctx]
  ; create a printer that accumulates your output
  (capture-output ctx
    ; do something and write messages to the output
    (println "Hello")
    (println "World")
    ; return your accumulated output in the :out value of your steps result
    {:status :success}))
```

At the moment, only clojures `*out*` is supported as Java interop support proved to be tricky to get right: Just calling `System/setOut` would re-set all-output, not just the output of the code within the scope of the step. There would be a way forward limiting the scope with a printer delegating to an `InheritableThreadLocal` keeping the output stream but that seemed a bit too complex and fragile to just implement right now. 

Feel free to re-open this issue if you have an urgent need for Java interop-support. Also, pull requests are always welcome.
