### ISSUE TITLE
Steps can not override :globals

### ISSUE THREAD

**Issue by SimonMonecke** [flosell/lambdacd#61]
If you have a pipeline with two steps setting the same :globals value you notice an issue: The second step can not override the global. Because of that you have the unchanged value after executing the second step.

|-> set-foobar {:status :succes :global {:foobar 42}} -> set-foobar {:status :succes :global {:foobar 43}} -> mul-foobar {:status :succes :global {:foobar 420}}

Test (execution.clj):
```clojure
(testing "that a step overrides a :global value"
    (is (= {:outputs {[1 0] {:status :success :global {:foobar 42}}
                      [2 0] {:status :success :global {:foobar 43}}
                      [3 0] {:status :success :foobar-times-ten 430}}
            :status  :success}
           (execute-steps [some-step-returning-global-foobar-value some-step-returning-another-global-foobar-value some-step-using-global-foobar-value] {} (some-ctx-with :step-id [0])))))
```

**Comment by flosell** [comment]
Thanks for reporting this and thanks for supplying a test for the issue! 
You are right, it probably makes sense to be able to overwrite a global value. At least, I can't come up with a scenario right now that would justify not allowing it. 

It's probably just an issue on how global values are being merged in `execution.clj`. So it might be a good entry-level task for a newcomer willing to start contributing. 

If not, I'll try to fix this before the next release.
