### ISSUE TITLE
Scroll pipeline to keep running step in focus

### ISSUE THREAD

**Issue by mananbharara** [flosell/lambdacd#64]
It might make more sense to automatically scroll the pipeline to the currently running step. Otherwise it becomes hard to understand the current state of the pipeline, especially in case of long pipelines.

**Comment by mrohte** [comment]
+1

**Comment by flosell** [comment]
@mananbharara, @mrohte:
Sorry, just noticed I never replied to this issue... 

The last two releases (0.5.7 and 0.6.0) added support for collapsing parts of the pipeline in the UI. Did this already help in understanding the state of the pipeline or is this issue still relevant?

**Comment by flosell** [comment]
Closing for now, feel free to reopen if this is still relevant
