### ISSUE TITLE
Subscribe to events?

### ISSUE THREAD

**Issue by alex-glv** [flosell/lambdacd#65]
Is there an option to shoot events to custom handlers when a build step is complete?
e.g. slack integration

Thanks!

**Comment by alex-glv** [comment]
I am using :event-publisher channel now. It would be nice to be able to pass custom handlers to project defined build steps

**Comment by flosell** [comment]
I guess you are already on the right track, you can subscribe to the `:step-finished`-event on the event-bus (that's not documented, I'll try to change that now) to be notified when a build step is complete: 

```clojure
(let [subscription (event-bus/subscribe context :step-finished)
      steps-finished (event-bus/only-payload subscription)]
  (async/go-loop []
    (if-let [event (async/<! steps-finished)]
      (do
        (do-something-with event)
        (recur)))))
```

Here is how the `start-new-run-after-first-step-finished`-runner uses this event to detect when to spawn a new pipeline run: 
https://github.com/flosell/lambdacd/blob/2e84fe8/src/clj/lambdacd/runners.clj#L20

There's also `:step-result-updated` if you are interested in updates while the step is still running. 

Not sure what you mean with "custom handlers to project defined build steps", could you give an example?

**Comment by flosell** [comment]
Here's a bit of documentation: https://github.com/flosell/lambdacd/wiki/Event-Bus
Feel free to edit in case something's wrong or missing

**Comment by flosell** [comment]
@alex-glv: Is this issue still relevant or did the explanations clarify the problem?

**Comment by flosell** [comment]
closing for now, feel free to reopen if still relevant
