### ISSUE TITLE
Trigger builds from any git branch change

### ISSUE THREAD

**Issue by wkral** [flosell/lambdacd#66]
It would be useful to have any git change trigger a build or test run.

A typical example for this is when you have people submitting pull requests from a feature branch the CI/CD server can start a build with that branch and then update the pull request on github/bitbucket/etc. with the results of the testing.

I maybe have missed something but it seems all the steps/git code currently is contextualized around a specific branch that you pass to the functions.

In any case I like what you're doing here and am interested in using this at my company, we're dipping our toes in right now. Ideally we'd like to contribute back so maybe this is the first thing if you're interested in this feature.

Thanks.

**Comment by flosell** [comment]
Hi, thanks for the feedback!

You are right, at least `wait-for-git` currently assumes that you wait for a specific branch. But your use case absolutely makes sense and should be supported. I'd be very happy about a pull request on this! 

`with-git` and `checkout-and-execute` are more general and they should work with any branch or revision so it's probably enough support waiting for changes on any branch.

**Comment by flosell** [comment]
I have started splitting out git-support into its own library to make it easier to maintain and contribute and cleaned up a lot of stuff along the way. 

I won't add features to git support in lambdacd-core but waiting on arbitrary branches will be in the new library: flosell/lambdacd-git#1
