### ISSUE TITLE
Multiple git branches question

### ISSUE THREAD

**Issue by jonocodes** [flosell/lambdacd#76]
Not sure this is appropriate for an issue tracker, but the docs say to reach out here...

I would like to build a system that runs an instance of my web app for every branch it git on a different (possibly random) ports. FYI, my app is running using Docker.

For example, lets say I have two branches in my project at some point in time: master and feature-foo

LambdaCD would listen to my git repo and keep updated branches deployed in an up to date state.
branch master would be hosted on localhost:1234
branch feature-foo would be hosted on localhost:4597

If a new branch feature-bar comes into existance, it would bring up a localhost:8241

I have been able to have LambdaCD maintain just deploying my 'master', but now I am trying to have it see other branches. I'm having a little trouble orchestrating this and want to be sure this is the right tool for the job.

Part of the problem is that the provided git library cant listen for branches coming in and out of existence. Instead I would have to watch the whole repo and compare checksums across all the branches or some such logic like that.

Am I trying to do too much with this tool? Am I thinking about this wrong? Does such a thing exist already in the open source world? I know heroku has a similar feature for its customers.

**Comment by flosell** [comment]
> Not sure this is appropriate for an issue tracker, but the docs say to reach out here...

That's perfectly ok!

> Am I trying to do too much with this tool? Am I thinking about this wrong? 

I think your basic problem is one that already appeared in #66, the fact that you are currently unable to wait for commits without giving a specific branch. I'm currently rethinking the git integration in general and I'll certainly keep your use case in mind. 

Once you know something happened on a particular branch, your existing pipeline for master would probably work just the same, plus maybe a bit of logic to map the branch name to a port. 

If you don't want to wait, until I implement this feature, triggers are no more than normal build steps that poll a repository until something happens so it's probably not impossible to build this yourself.

There are two other ways you could model this right now that might even give you a better visibility than the above approach. 
Both are based on dynamically generating pipelines: 

* `either` with lots of waiting steps: The most straightforward thing to do when you don't have a feature that can detect commits on arbitrary branches, you just set up a trigger for every branch you are interested in and wrap them in an `either`: 

  ```clojure
  (either
    wait-for-commit-on-master
    wait-for-commit-on-feature-foo
   ; ...
  )
  ```
  Obviously, that's very tedious if you need to maintain this manually. But LambdaCD also allows you to generate pipelines dynamically, upon initialization (might even work at runtime, haven't tried that yet).
  So you could pull a list of branches when initializing and generate a pipeline on the fly with a `wait-for` for every branch. 
* a pipeline for every branch: Just as you can create a pipeline with a dynamic part, you can also generate more than one pipeline with the same structure but different parameters. In your case, a new pipeline instance for every branch.

You'll find pointers and links to sample projects [here](https://github.com/flosell/lambdacd/blob/master/doc/howto.md#how-do-i-generate-several-pipelines-with-the-same-structure), [here](https://github.com/flosell/lambdacd/wiki/Guide:-Pipeline-Structure-Refactoring#step-3-removing-structural-duplication) and [here](https://github.com/flosell/lambdacd/wiki/Pipeline-Structure-DSL).


> Does such a thing exist already in the open source world? 
I would guess that something similar would also be possible in tools like Jenkins and GoCD, not sure how much pain would be involved though :) 

If using a hosted service is an option for you (and those are powerful enough for what you are trying to do), I think both TravisCI and SnapCI (probably others as well) can be triggered by arbitrary branches. They are probably using github webhooks to detect new branches (I don't support something like this out of the box right now, but it's certainly doable as well).

**Comment by jonocodes** [comment]
Thanks for the tips.

I have been torn between doing this in LambdaCD, possibly writing a Jenkins plugin, or creating a web app from scratch to do this (probably using meteorjs). All of these options I am no expert at. I want this to be a general solution for my web projects so I would rather go open source then hosted.

I just tried your second bullet point and it seems to have the base functionality. I followed the template here:
https://github.com/flosell/lambdacd-cookie-cutter-pipeline-example/blob/master/src/pipeline_templates/pipeline.clj

So this takes care of listening to each branch for changes. What I'm missing now is a way to discover new branches coming in and out of existence.

Perhaps I could implement an additional git listener that listens to the whole repo and then I examine the commit that changed and check it against the running branches. My 2 questions are
1. where would I put this git listener since it would be a step outside the pipelines?
2. if I detect a new branch, how would I add a link to the existing index page while lambdacd is running?

**Comment by jonocodes** [comment]
Actually I seem to have figured out how to regenerate the index. Now I am trying to figure out how to generate the pipelines dynamically as needed.

**Comment by flosell** [comment]
Sorry for the late reply, great to hear you are making progress!

Some comments: 

You are right, the pipelines are initialized when the server starts. specifically, here: https://github.com/flosell/lambdacd-cookie-cutter-pipeline-example/blob/master/src/pipeline_templates/pipeline.clj#L36

This initializes a complete instance of LambdaCD including a thread (`runner`) that starts new runs of the given pipeline. One thing to watch out for: Those runners currently cannot be stopped (which you might want to do if a branch is deleted). I have created an issue for this: #78

In general, as you might already noticed, I have never tried creating and killing pipelines in such a dynamic fashion so we are moving into unchartered territory the more dynamic we make it. 

Because of that, I'd probably approach it step-by-step, maybe starting with a hardcoded list of branches, replacing those with a list that's generated when the server starts (that would already "solve" your problem, you'd just need to restart every time your branches change ;-)) and then replacing that with a solution that can change on the fly. 

And tell me about the roadblocks you find along the way! More complicated or custom use-cases like this are exactly what LambdaCD was built for so getting feedback on where it doesn't support you are very valuable!

**Comment by jonocodes** [comment]
Thanks for your help.

I have made more progress. I have posted my code, so you can see what I am trying to do. I have the index page working, but I'm stuck at creating contexts on the fly.

The app currently creates a route for each branch (ie - localhost:8080/develop). These need to be created at start. But I thought I could change the routes to use path parameters so I can create the context and pipeline on the fly. That is failing with a 404. A path would be localhost:8080/branch/develop

Here is where I am generating the pipeline and the route UI:
https://github.com/jonocodes/branch-runner-lcd/blob/7a5f95946bcabf2bb73e21d1304e6bdd6af3e1c6/src/branch_runner/pipeline.clj#L113

Not sure if the problem lies in clojure, LambdaCD, ring, or compojure. Maybe you have an idea.

**Comment by flosell** [comment]
I just sent you a pull request with some pointers how to fix this. You'll find details there.

**Comment by jonocodes** [comment]
Thanks. Thats just was I was looking for. Now I have it creating pipelines when the app starts and allowing them to be accessed from that path param route.

**Comment by flosell** [comment]
Any open questions on this? Otherwise, I'd close this issue.

**Comment by jonocodes** [comment]
No more questions on this. Thanks.
