### ISSUE TITLE
Taming logging

### ISSUE THREAD

**Issue by jonocodes** [flosell/lambdacd#77]
I cant seem to figure out how to manage the log output. I have tried placing log4j.properties files in every directory and tried setting lots of different configs in the code but I am still getting DEBUG output from lambdacd.* and done a lot of googling.

Is there an example I could use?

**Comment by flosell** [comment]
LambdaCD uses Logback, not Log4j. 

Place a `logback.xml` file in your projects `resources/` folder to configure it. Here's an example: https://github.com/flosell/lambdacd/blob/master/resources/logback.xml

This wasn't documented yet but is now: https://github.com/flosell/lambdacd/wiki/Logging
Thanks for reminding me!

Also, I should maybe include such a sample in the project template to simplify this...

**Comment by jonocodes** [comment]
Thanks, Thats what I needed.
