### ISSUE TITLE
Can't control where `with-workspace` creates tmp work directory

### ISSUE THREAD

**Issue by philwhln** [flosell/lambdacd#79]
For our use-case we need to control where the temporary working directory of a build is created. Since `create-temp-dir` is called from `with-workspace` [without a `parent` arg](https://github.com/flosell/lambdacd/blob/17821efdc199c8adb1ff8c199c5c7359590adc11/src/clj/lambdacd/steps/control_flow.clj#L122) it is created in a location that is inaccessible to our build step. This is different behaviour to `lambdacd.steps.git/with-git-branch` which [uses the parent of the `home-dir`](https://github.com/flosell/lambdacd/blob/4eee96caa58147ea0469a9d6a5f7124f50e7e735/src/clj/lambdacd/steps/git.clj#L74).

I'm looking to provide a PR for this, but since I'm fairly new to Clojure and lambdacd I thought best to document this first, before I venture into the code.

**Comment by flosell** [comment]
Hey, thanks for pointing this out! You are right, `with-workspace` should write to the home-dir.

I'd love a pull request on this.

**Comment by philwhln** [comment]
Thanks for the quick feedback!

> I'd love a pull request on this.

Working on it now
