### ISSUE TITLE
Add a feature to customize UI Page

### ISSUE THREAD

**Issue by flosell** [flosell/lambdacd#83]
Use Cases: 
* Users with lots of pipelines want to add navigation bars to jump between pipelines
* Users just want to customize their look and feel, add corporate identity, ... 

Potential Solutions: 
* Provide a way to swap the whole UI page handler (adding convenience functions to embed required resources and the UI into custom hiccup)
* Provide a way to swap just the header

**Comment by philwhln** [comment]
+1

**Comment by flosell** [comment]
Made routes and page assembly more modularized so you can swap out the UI page with something else. For an example of how to implement a navbar, see https://github.com/flosell/lambdacd-cookie-cutter-pipeline-example/blob/header-with-navigation/src/pipeline_templates/custom_ui.clj
