### ISSUE TITLE
Instead of polling, wait for push notifications from version control server

### ISSUE THREAD

**Issue by ftravers** [flosell/lambdacd#87]
It would be nice to instead of polling the git repo, instead have a URL that the git server can hit to indicate that new code has been checked in and a build needs to happen.

**Comment by flosell** [comment]
Agreed, this sounds like an interesting feature. 
At the moment, there are two ways of accomplishing this: 

* **the manual trigger way**: `wait-for-manual-trigger` is a build-step that just waits until a POST request with a random UUID generated for this run of the step (to distinguish triggers if there's more than one per pipeline and more than one run in parallel). If your setup allows you to create custom git-hooks, you could probably script the LambdaCD API to achieve this. Not really elegant but should work right now
* [**the jenkins way**](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin#GitPlugin-Pushnotificationfromrepository): Jenkins allows you to just send a notification about a commit in a repo. We could do the same thing and let `wait-for-git` use that information. Probably the preferred solution in the longer term. I'm planning to deprecate the build-in git support in favor of [lambdacd-git](https://github.com/flosell/lambdacd-git), a new, more maintainable, robust implementation (you can probably use it right now, I'm just waiting for feedback from some early adopters before officially announcing it) so I probably won't implement it here. I'm tracking this in the other project though (flosell/lambdacd-git#6)

**Comment by flosell** [comment]
This is now implemented in [lambdacd-git](https://github.com/flosell/lambdacd-git#using-web--or-post-commit-hooks-instead-of-polling), closing this issue as the git implementation in this repo will be deprecated soon
