### ISSUE TITLE
(Question) Easy way to change pipeline state

### ISSUE THREAD

**Issue by konradjurk** [flosell/lambdacd#94]
I have a couple of optional steps in my pipeline so I implemented a custom pipeline-runner which spawns a new pipeline after the required steps are done. This is cool but leaves most of the builds with a yellow "paused" icon. When the required part is done, I would like to mark runs with a green checkmark as successful. Is it possible to access the run from within my pipeline-runner and just change the state?

**Comment by flosell** [comment]
The overall build status is just the last known status in the pipeline: https://github.com/flosell/lambdacd/blob/master/src/clj/lambdacd/presentation/pipeline_state.clj#L23

Consequently, you need your pipeline to "finish" to get the result like this. 

I imagine you have a pipeline like this: 

```clojure
`(build-step-1
  build-step-2
  optional-build-step-1
  optional-build-step-2)
```

Two things you could try to get your pipeline to finish: 

If you are able to decide when the optional steps need to run and when not to run (e.g. through a flag when the pipeline is triggered), you can use `junction`: 

```clojure
`(build-step-1
  build-step-2
  (junction
    need-to-run-optionals? 
    (run 
      optional-build-step-1
      optional-build-step-2)
    do-something-else))
```

If that isn't possible, you could create a custom `fire-and-forget` control-flow that executes the optional steps in the background but itself returns immediately, finishing the pipeline: 

```clojure
`(build-step-1
  build-step-2
  (fire-and-forget
    optional-build-step-1
    optional-build-step-2))
```

You could probably draw inspiration from `either` and `in-parallel` to do that. You might need to have your own `:unify-status-fn` as well to make sure the status is aggregated the way you want it.

**Comment by konradjurk** [comment]
My pipeline looks like this:

```
(def pipeline-def
  `(
     (either
       manualtrigger/wait-for-manual-trigger
       wait-for-commit)
     (with-repository
       (alias "Run Tests"
         (run
           backend-unittests
           backend-integrationtest))
       (alias "Release Components"
         (in-parallel
           (alias "Frontend"
             (run
               manualtrigger/wait-for-manual-trigger
               release-frontend
               build-frontend-image))
           (alias "Backend"
             (run
               manualtrigger/wait-for-manual-trigger
               release-backend
               build-backend-image)))))))
```

Most of the time the pipeline is triggered due to git commits, so at this point there is no user who can decide whether or not the optional steps (everything under alias "Release Components") should run, so I used two manual triggers for that which means the pipeline can't "finish" like you suggested :(

**Comment by flosell** [comment]
In this case, the fire-and-forget approach is probably what I'd go for. 

Although from a pipeline modelling standpoint, the way LambdaCD currently displays it would be more correct: your pipeline goes from commit to release. Until your release is done, your pipeline isn't "done". 
In this sense, if releases only happen rarely, maybe the release would be a separate pipeline that can be triggered whenever a release is needed. This is probably what GoCD would do and it's probably overkill though for pipelines your size. Also, to be honest, I haven't put too much thought on what orchestration between multiple pipelines would look like so you'd be in unchartered territory there :)

**Comment by konradjurk** [comment]
Hm the additional pipeline sounds like the way to go. Can I link to different lambdacd pipeline and pass parameters for the build?

**Comment by flosell** [comment]
I haven't built anything to link pipelines together yet. You could proably use something similar to the manual trigger (https://github.com/flosell/lambdacd/blob/master/src/clj/lambdacd/steps/manualtrigger.clj) to trigger one pipeline from the other.

**Comment by flosell** [comment]
Do you still need help here? If not, I'd close this issue for now. Also, I'd be really interested in feedback what approach you went with and how that worked out. So feel free to ping me.

**Comment by konradjurk** [comment]
Thanks, I'm sure I'll need your help in the future but we can close this for now :) I'll let you know what approach worked best for me!
