### ISSUE TITLE
Manual trigger should always indicate its triggerability

### ISSUE THREAD

**Issue by aepsil0n** [flosell/lambdacd#97]
A small user experience report about an issue that confused us while working on a pipeline: there is no play button on manual triggers, unless the pipeline actually reaches that step. We thought for quite a while that we somehow messed up our setup, until we actually reached that step.

In that process we also upgraded to 0.7.1, which appears to have fixed an issue where we never saw the play button. But still, I feel it makes sense to always show something, even if it does not make sense to interact with it, e.g. a grayed-out play button to indicate that at some point you may be able to manually trigger the step at some point, but not now.

**Comment by flosell** [comment]
thanks for the feedback, I can see how this makes sense. 

The reason you only see the play button once you reach that step is simply that LambdaCD currently detects manual triggers by looking at the (in this case intermedate) step-result. 

We could probably improve this by adding metadata to the step to indicate it's a manual trigger, similar to the `:display-type` in [control-flow steps](https://github.com/flosell/lambdacd/blob/master/src/clj/lambdacd/steps/control_flow.clj#L40):

**Comment by flosell** [comment]
Done: 
<img width="416" alt="screen shot 2016-03-20 at 16 27 07" src="https://cloud.githubusercontent.com/assets/540525/13905206/3298b090-eeb9-11e5-9a0d-694c452e6af0.png">
